# Generated by Django 4.2.23 on 2025-09-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoplay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='hot_tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_img',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
