# Generated by Django 4.2.23 on 2025-09-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoplay', '0002_movie_hot_tag_movie_movie_img_movie_movie_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_name',
            field=models.CharField(default='未知电影', max_length=100),
        ),
    ]
